### ISSUE TITLE
Issue with Checkout on Cart.

### ISSUE THREAD

**Issue by tylerkrett** [paylike/plugin-opencart-3#10]
Dear Paylike,

I Hope all is well.

Currently we are using this plugin and our getting issues with the API calls as we initially get a 400 (3--D secure is required.)
from what I can see in the post we have all the fields filled in. Then another request gets fired with the same info and passes taking the payment but breaking the Opencart form from Processing. 

We also get a message saying invalid transaction.

I then reinstalled the extension and now cannot save the form for editing on the management side as it says "The live App Key is required!" and "The live Public Key is required!" when they are filled in.

payment_paylike_status: 0
payment_paylike_method_title: Credit Card
payment_paylike_checkout_cc_logo[]: mastercard.png
payment_paylike_checkout_cc_logo[]: maestro.png
payment_paylike_checkout_cc_logo[]: visa.png
payment_paylike_checkout_cc_logo[]: visaelectron.png
payment_paylike_checkout_title: 
payment_paylike_api_mode: test
payment_paylike_app_key_test: 5ef79068877d5459544xxxxx
payment_paylike_public_key_test: 29536615-87ee-47fb-9a5b-b5f09bxxxxxx
payment_paylike_app_key_live: 
payment_paylike_public_key_live: 
payment_paylike_capture_mode: delayed
payment_paylike_authorize_status_id: 1
payment_paylike_capture_status_id: 5
payment_paylike_refund_status_id: 11
payment_paylike_void_status_id: 16
payment_paylike_logging: 0
payment_paylike_store[]: 0
payment_paylike_minimum_total: 0
payment_paylike_geo_zone: 0
payment_paylike_sort_order: 0

current request being sent that gets the error of the field not being valid for test one.

Version I am using is the latest version of paylike extension and my Opencart Version is  3.0.2.0

**Comment by ionutcalara** [comment]
Hi @tylerkrett it does look that you are using the wrong app key, you seem to be using the merchant id and not the app key. Please create a new app from the right of the screen where you copied the keys. If you still have issues let me know. I will close this ticket but feel free to reopen.

**Comment by tylerkrett** [comment]
Thank you for all your assistance all working now
