### ISSUE TITLE
Opencart 3.0.3.7. + Journal 3.1.8 3D Secure problem

### ISSUE THREAD

**Issue by Elryndel** [paylike/plugin-opencart-3#15]
Hi there!

We now integrated the Paylike payment method to our shop (https://cardmeee.com), but when try to buy something the payment always failed, with "3D secure is requied (30)" error. I attached a screenshot without the personal datas about the error. We tried 3 credit card and not worked.

The test version of the payment is worked well with the test account and the test card (4100 0000 0000 0000), but the live is drop this error every time :/

Every credit card is registered in Hungary, at the OTP Bank.

![Screenshot 2021-02-26 20 31 17](https://user-images.githubusercontent.com/79720742/109346817-85b88780-7872-11eb-90c4-c09288edb8c1.png)

**Comment by ionutcalara** [comment]
Hi there, there's a new update that updates the sdk version in the plugin. You can get it here: https://github.com/paylike/plugin-opencart-3/blob/master/paylike.ocmod.zip

Let me know if you still have issues, feel free to reopen.
